# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWritingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('target_milestone_word_count', models.PositiveIntegerField(default=700)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_words_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
